apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-rlipuktd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-rlipuktd 
  name: go-rlipuktd
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-rlipuktd
    weight: 100 
